---
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
        stages: [pre-commit]

      - id: end-of-file-fixer
        stages: [pre-commit]

      - id: trailing-whitespace
        stages: [pre-commit]

      - id: check-yaml
        stages: [pre-commit]

      - id: detect-private-key
        stages: [pre-commit]

      - id: check-executables-have-shebangs
        stages: [pre-commit]

      - id: check-shebang-scripts-are-executable
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
